#ifndef SCENES_H
#define SCENES_H

#include <string>

using std::string;
struct Scenes
{
	int maxSizeRows;
	int maxSizeCols;
	std::string menu;
	std::string lose;
	std::string win;
	std::string level1;
	std::string level2;
	std::string level3;
	std::string level4;
	std::string level5;
	std::string border;

	Scenes()
	{
		maxSizeCols = 30;
		maxSizeRows = 29;

		border  = "#############################\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#                           #\n";
		border += "#############################\n";

		menu  = "#############################\n";
		menu += "#                           #\n";
		menu += "#         Welcome           #\n";
		menu += "#                           #\n";
		menu += "#           to              #\n";
		menu += "#                           #\n";
		menu += "#       Space Raiders       #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#     press 'p' to play     #\n";
		menu += "#     press 'q' to quit     #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "# programmed by Kaleb Alanis#\n";
		menu += "#     Github:: koalanis     #\n";
		menu += "#                           #\n";
		menu += "#                           #\n";
		menu += "#############################\n";


		lose = "#############################\n";
		lose += "#                           #\n";
		lose += "#         You LOSE          #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#       Your Score ::       #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#   press  'p' to restart   #\n";
		lose += "#   press  'q' to quit      #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#  program by Kaleb Alanis  #\n";
		lose += "#     Github:: koalanis     #\n";
		lose += "#                           #\n";
		lose += "#                           #\n";
		lose += "#############################\n";

		win = "#############################\n";
		win += "#                           #\n";
		win += "#          You WIN          #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#   press   'p' to restart  #\n";
		win += "#   press   'q' to quit     #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#  program by Kaleb Alanis  #\n";
		win += "#     Github:: koalanis     #\n";
		win += "#                           #\n";
		win += "#                           #\n";
		win += "#############################\n";

		level1 =  "#############################\n";
		level1 += "#                           #\n";
		level1 += "#        WuWuWuWuWuW        #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#                           #\n";
		level1 += "#              ^            #\n";
		level1 += "#                           #\n";
		level1 += "#############################\n";



		level2 = "#############################\n";
		level2 += "#                           #\n";
		level2 += "#        WuWuWuWuWuW        #\n";
		level2 += "#        WuWuWuWuWuW        #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#                           #\n";
		level2 += "#              ^            #\n";
		level2 += "#                           #\n";
		level2 += "#############################\n";


		level3 =  "#############################\n";
		level3 += "#                           #\n";
		level3 += "#        WuWuWuWuWuW        #\n";
		level3 += "#        WuWuWuWuWuW        #\n";
		level3 += "#        WuWuWuWuWuW        #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#                           #\n";
		level3 += "#              ^            #\n";
		level3 += "#                           #\n";
		level3 += "#############################\n";


		level4 = "#############################\n";
		level4 += "#                           #\n";
		level4 += "#        WuWuWuWuWuW        #\n";
		level4 += "#        WuWuWuWuWuW        #\n";
		level4 += "#        WuWuWuWuWuW        #\n";
		level4 += "#        WuWuWuWuWuW        #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#                           #\n";
		level4 += "#              ^            #\n";
		level4 += "#                           #\n";
		level4 += "#############################\n";

		level5 = "#############################\n";
		level5 += "#                           #\n";
		level5 += "#        WuWuWuWuWuW        #\n";
		level5 += "#        WuWuWuWuWuW        #\n";
		level5 += "#        WuWuWuWuWuW        #\n";
		level5 += "#        WuWuWuWuWuW        #\n";
		level5 += "#        WuWuWuWuWuW        #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#                           #\n";
		level5 += "#              ^            #\n";
		level5 += "#                           #\n";
		level5 += "#############################\n";
	}

};

#endif
